[0m21:40:56.037830 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA62459580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA61D79820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6249CBF0>]}


============================== 21:40:56.042834 | 31c97776-c48d-4ba0-bebd-80a3c32ec5b2 ==============================
[0m21:40:56.042834 [info ] [MainThread]: Running with dbt=1.8.2
[0m21:40:56.043829 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '../', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:41:28.970469 [debug] [MainThread]: Starter project path: C:\Users\FellipeGuedes\Documents\code\dw\.venv\Lib\site-packages\dbt\include\starter_project
[0m21:41:28.995151 [info ] [MainThread]: 
Your new dbt project "datawarehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:41:28.996156 [info ] [MainThread]: Setting up your profile.
[0m21:43:23.279932 [info ] [MainThread]: Profile datawarehouse written to ..\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:43:23.280936 [debug] [MainThread]: Command `dbt init` succeeded at 21:43:23.280936 after 147.34 seconds
[0m21:43:23.282122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA624A6A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA6276E4B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AA622623F0>]}
[0m21:43:23.282122 [debug] [MainThread]: Flushing usage events
[0m22:49:00.996212 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278457953A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278451F9DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027842214530>]}


============================== 22:49:01.000211 | 373a55dd-719b-445a-852e-8604a0c5222e ==============================
[0m22:49:01.000211 [info ] [MainThread]: Running with dbt=1.8.2
[0m22:49:01.001212 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '../', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:49:01.001212 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\FellipeGuedes\Documents\code\dw\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:49:01.002306 [debug] [MainThread]: Command `dbt run` failed at 22:49:01.002306 after 0.11 seconds
[0m22:49:01.003311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027845386480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278457953A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027845A32600>]}
[0m22:49:01.003311 [debug] [MainThread]: Flushing usage events
